# Generated by Django 3.2.2 on 2021-06-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_auto_20210526_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['id'], 'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
