# Generated by Django 3.2.2 on 2021-05-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Depa',
            new_name='Departamento',
        ),
    ]
